# Generated by Django 3.2.7 on 2021-10-01 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tecnology',
            options={'verbose_name_plural': 'Tecnologies'},
        ),
    ]
