# Generated by Django 3.2.7 on 2021-10-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0002_alter_tecnology_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projeto',
            new_name='Project',
        ),
    ]
