# Generated by Django 3.2.7 on 2021-10-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0003_rename_projeto_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnology',
            name='label',
            field=models.CharField(max_length=50, unique=True, verbose_name='Label'),
        ),
    ]
