# Generated by Django 3.2.7 on 2021-10-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0007_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
