# Generated by Django 3.2.7 on 2021-10-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0011_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('bot', 'Bot'), ('api', 'API'), ('site', 'Website')], default='site', max_length=10, verbose_name='Type'),
        ),
    ]
