# Generated by Django 3.2.7 on 2021-10-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0012_alter_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.CharField(default='a', max_length=1, verbose_name='order'),
        ),
    ]
