# Generated by Django 3.2.7 on 2021-10-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0013_skill_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.CharField(default='a', max_length=5, verbose_name='order'),
        ),
    ]
