# Generated by Django 3.2.7 on 2021-10-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0014_alter_skill_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentlyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_welcome', models.TextField(verbose_name='Descrição Welcome')),
                ('funcao', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=255)),
                ('descricao_about_me', models.TextField(verbose_name='Descrição Sobre mim')),
            ],
        ),
    ]
