# Generated by Django 3.2.7 on 2021-10-06 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0015_currentlyactivity_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentlyactivity',
            name='profile_fk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portifolio.profile'),
            preserve_default=False,
        ),
    ]
