# Generated by Django 3.2.7 on 2021-12-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0016_currentlyactivity_profile_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='menu_foto',
            field=models.FileField(blank=True, null=True, upload_to='media/images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_foto',
            field=models.FileField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
