# Generated by Django 3.2.7 on 2021-12-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0017_auto_20211221_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='menu_foto',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_foto',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
